//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentacion.wsMenuDia {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsMenuDia.IWcfMenuDia")]
    public interface IWcfMenuDia {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/GuardarMenuDia", ReplyAction="http://tempuri.org/IWcfMenuDia/GuardarMenuDiaResponse")]
        Entidades.MenuDiaEntidad GuardarMenuDia(Entidades.MenuDiaEntidad menuDia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/GuardarMenuDia", ReplyAction="http://tempuri.org/IWcfMenuDia/GuardarMenuDiaResponse")]
        System.Threading.Tasks.Task<Entidades.MenuDiaEntidad> GuardarMenuDiaAsync(Entidades.MenuDiaEntidad menuDia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/DevolverListaMenuDia", ReplyAction="http://tempuri.org/IWcfMenuDia/DevolverListaMenuDiaResponse")]
        Entidades.MenuDiaEntidad[] DevolverListaMenuDia();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/DevolverListaMenuDia", ReplyAction="http://tempuri.org/IWcfMenuDia/DevolverListaMenuDiaResponse")]
        System.Threading.Tasks.Task<Entidades.MenuDiaEntidad[]> DevolverListaMenuDiaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/DevolverListaMenuDiaJoin", ReplyAction="http://tempuri.org/IWcfMenuDia/DevolverListaMenuDiaJoinResponse")]
        Entidades.MenuDiaJoin[] DevolverListaMenuDiaJoin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/DevolverListaMenuDiaJoin", ReplyAction="http://tempuri.org/IWcfMenuDia/DevolverListaMenuDiaJoinResponse")]
        System.Threading.Tasks.Task<Entidades.MenuDiaJoin[]> DevolverListaMenuDiaJoinAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/DevolverMenuDiaPorId", ReplyAction="http://tempuri.org/IWcfMenuDia/DevolverMenuDiaPorIdResponse")]
        Entidades.MenuDiaEntidad DevolverMenuDiaPorId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/DevolverMenuDiaPorId", ReplyAction="http://tempuri.org/IWcfMenuDia/DevolverMenuDiaPorIdResponse")]
        System.Threading.Tasks.Task<Entidades.MenuDiaEntidad> DevolverMenuDiaPorIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/EliminarMenuDia", ReplyAction="http://tempuri.org/IWcfMenuDia/EliminarMenuDiaResponse")]
        bool EliminarMenuDia(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/EliminarMenuDia", ReplyAction="http://tempuri.org/IWcfMenuDia/EliminarMenuDiaResponse")]
        System.Threading.Tasks.Task<bool> EliminarMenuDiaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/DevolverMenuDiaPorFecha", ReplyAction="http://tempuri.org/IWcfMenuDia/DevolverMenuDiaPorFechaResponse")]
        Entidades.MenuDiaEntidad[] DevolverMenuDiaPorFecha(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/DevolverMenuDiaPorFecha", ReplyAction="http://tempuri.org/IWcfMenuDia/DevolverMenuDiaPorFechaResponse")]
        System.Threading.Tasks.Task<Entidades.MenuDiaEntidad[]> DevolverMenuDiaPorFechaAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/GuardarSopa", ReplyAction="http://tempuri.org/IWcfMenuDia/GuardarSopaResponse")]
        Entidades.SopasEntidad GuardarSopa(Entidades.SopasEntidad sopaDia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/GuardarSopa", ReplyAction="http://tempuri.org/IWcfMenuDia/GuardarSopaResponse")]
        System.Threading.Tasks.Task<Entidades.SopasEntidad> GuardarSopaAsync(Entidades.SopasEntidad sopaDia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/DevolverListaSopas", ReplyAction="http://tempuri.org/IWcfMenuDia/DevolverListaSopasResponse")]
        Entidades.SopasEntidad[] DevolverListaSopas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/DevolverListaSopas", ReplyAction="http://tempuri.org/IWcfMenuDia/DevolverListaSopasResponse")]
        System.Threading.Tasks.Task<Entidades.SopasEntidad[]> DevolverListaSopasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/DevolverSopasPorId", ReplyAction="http://tempuri.org/IWcfMenuDia/DevolverSopasPorIdResponse")]
        Entidades.SopasEntidad DevolverSopasPorId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/DevolverSopasPorId", ReplyAction="http://tempuri.org/IWcfMenuDia/DevolverSopasPorIdResponse")]
        System.Threading.Tasks.Task<Entidades.SopasEntidad> DevolverSopasPorIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/EliminarSopa", ReplyAction="http://tempuri.org/IWcfMenuDia/EliminarSopaResponse")]
        bool EliminarSopa(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/EliminarSopa", ReplyAction="http://tempuri.org/IWcfMenuDia/EliminarSopaResponse")]
        System.Threading.Tasks.Task<bool> EliminarSopaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/DevolverIngredientesSopasPorId", ReplyAction="http://tempuri.org/IWcfMenuDia/DevolverIngredientesSopasPorIdResponse")]
        Entidades.SopasEntidad DevolverIngredientesSopasPorId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/DevolverIngredientesSopasPorId", ReplyAction="http://tempuri.org/IWcfMenuDia/DevolverIngredientesSopasPorIdResponse")]
        System.Threading.Tasks.Task<Entidades.SopasEntidad> DevolverIngredientesSopasPorIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/GuardarSegundo", ReplyAction="http://tempuri.org/IWcfMenuDia/GuardarSegundoResponse")]
        Entidades.SegundosEntidad GuardarSegundo(Entidades.SegundosEntidad segundo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/GuardarSegundo", ReplyAction="http://tempuri.org/IWcfMenuDia/GuardarSegundoResponse")]
        System.Threading.Tasks.Task<Entidades.SegundosEntidad> GuardarSegundoAsync(Entidades.SegundosEntidad segundo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/DevolverListaSegundos", ReplyAction="http://tempuri.org/IWcfMenuDia/DevolverListaSegundosResponse")]
        Entidades.SegundosEntidad[] DevolverListaSegundos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/DevolverListaSegundos", ReplyAction="http://tempuri.org/IWcfMenuDia/DevolverListaSegundosResponse")]
        System.Threading.Tasks.Task<Entidades.SegundosEntidad[]> DevolverListaSegundosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/DevolverSegundosPorId", ReplyAction="http://tempuri.org/IWcfMenuDia/DevolverSegundosPorIdResponse")]
        Entidades.SegundosEntidad DevolverSegundosPorId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/DevolverSegundosPorId", ReplyAction="http://tempuri.org/IWcfMenuDia/DevolverSegundosPorIdResponse")]
        System.Threading.Tasks.Task<Entidades.SegundosEntidad> DevolverSegundosPorIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/EliminarSegundo", ReplyAction="http://tempuri.org/IWcfMenuDia/EliminarSegundoResponse")]
        bool EliminarSegundo(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/EliminarSegundo", ReplyAction="http://tempuri.org/IWcfMenuDia/EliminarSegundoResponse")]
        System.Threading.Tasks.Task<bool> EliminarSegundoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/DevolverIngredientesSegundoPorId", ReplyAction="http://tempuri.org/IWcfMenuDia/DevolverIngredientesSegundoPorIdResponse")]
        Entidades.SegundosEntidad DevolverIngredientesSegundoPorId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/DevolverIngredientesSegundoPorId", ReplyAction="http://tempuri.org/IWcfMenuDia/DevolverIngredientesSegundoPorIdResponse")]
        System.Threading.Tasks.Task<Entidades.SegundosEntidad> DevolverIngredientesSegundoPorIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/GuardarBebida", ReplyAction="http://tempuri.org/IWcfMenuDia/GuardarBebidaResponse")]
        Entidades.BebidasEntidad GuardarBebida(Entidades.BebidasEntidad bebidas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/GuardarBebida", ReplyAction="http://tempuri.org/IWcfMenuDia/GuardarBebidaResponse")]
        System.Threading.Tasks.Task<Entidades.BebidasEntidad> GuardarBebidaAsync(Entidades.BebidasEntidad bebidas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/DevolverListaBebidas", ReplyAction="http://tempuri.org/IWcfMenuDia/DevolverListaBebidasResponse")]
        Entidades.BebidasEntidad[] DevolverListaBebidas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/DevolverListaBebidas", ReplyAction="http://tempuri.org/IWcfMenuDia/DevolverListaBebidasResponse")]
        System.Threading.Tasks.Task<Entidades.BebidasEntidad[]> DevolverListaBebidasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/DevolverBebidasPorId", ReplyAction="http://tempuri.org/IWcfMenuDia/DevolverBebidasPorIdResponse")]
        Entidades.BebidasEntidad DevolverBebidasPorId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/DevolverBebidasPorId", ReplyAction="http://tempuri.org/IWcfMenuDia/DevolverBebidasPorIdResponse")]
        System.Threading.Tasks.Task<Entidades.BebidasEntidad> DevolverBebidasPorIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/EliminarBebida", ReplyAction="http://tempuri.org/IWcfMenuDia/EliminarBebidaResponse")]
        bool EliminarBebida(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/EliminarBebida", ReplyAction="http://tempuri.org/IWcfMenuDia/EliminarBebidaResponse")]
        System.Threading.Tasks.Task<bool> EliminarBebidaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/DevolverIngredientesBebidaPorId", ReplyAction="http://tempuri.org/IWcfMenuDia/DevolverIngredientesBebidaPorIdResponse")]
        Entidades.BebidasEntidad DevolverIngredientesBebidaPorId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/DevolverIngredientesBebidaPorId", ReplyAction="http://tempuri.org/IWcfMenuDia/DevolverIngredientesBebidaPorIdResponse")]
        System.Threading.Tasks.Task<Entidades.BebidasEntidad> DevolverIngredientesBebidaPorIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/GuardarEntrada", ReplyAction="http://tempuri.org/IWcfMenuDia/GuardarEntradaResponse")]
        Entidades.EntradasEntidad GuardarEntrada(Entidades.EntradasEntidad entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/GuardarEntrada", ReplyAction="http://tempuri.org/IWcfMenuDia/GuardarEntradaResponse")]
        System.Threading.Tasks.Task<Entidades.EntradasEntidad> GuardarEntradaAsync(Entidades.EntradasEntidad entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/DevolverListaEntrada", ReplyAction="http://tempuri.org/IWcfMenuDia/DevolverListaEntradaResponse")]
        Entidades.EntradasEntidad[] DevolverListaEntrada();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/DevolverListaEntrada", ReplyAction="http://tempuri.org/IWcfMenuDia/DevolverListaEntradaResponse")]
        System.Threading.Tasks.Task<Entidades.EntradasEntidad[]> DevolverListaEntradaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/DevolverEntradasPorId", ReplyAction="http://tempuri.org/IWcfMenuDia/DevolverEntradasPorIdResponse")]
        Entidades.EntradasEntidad DevolverEntradasPorId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/DevolverEntradasPorId", ReplyAction="http://tempuri.org/IWcfMenuDia/DevolverEntradasPorIdResponse")]
        System.Threading.Tasks.Task<Entidades.EntradasEntidad> DevolverEntradasPorIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/EliminarEntrada", ReplyAction="http://tempuri.org/IWcfMenuDia/EliminarEntradaResponse")]
        bool EliminarEntrada(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/EliminarEntrada", ReplyAction="http://tempuri.org/IWcfMenuDia/EliminarEntradaResponse")]
        System.Threading.Tasks.Task<bool> EliminarEntradaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/DevolverIngredientesEntradaPorId", ReplyAction="http://tempuri.org/IWcfMenuDia/DevolverIngredientesEntradaPorIdResponse")]
        Entidades.EntradasEntidad DevolverIngredientesEntradaPorId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/DevolverIngredientesEntradaPorId", ReplyAction="http://tempuri.org/IWcfMenuDia/DevolverIngredientesEntradaPorIdResponse")]
        System.Threading.Tasks.Task<Entidades.EntradasEntidad> DevolverIngredientesEntradaPorIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/GuardarPedido", ReplyAction="http://tempuri.org/IWcfMenuDia/GuardarPedidoResponse")]
        Entidades.PedidosEntidad GuardarPedido(Entidades.PedidosEntidad pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfMenuDia/GuardarPedido", ReplyAction="http://tempuri.org/IWcfMenuDia/GuardarPedidoResponse")]
        System.Threading.Tasks.Task<Entidades.PedidosEntidad> GuardarPedidoAsync(Entidades.PedidosEntidad pedido);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWcfMenuDiaChannel : Presentacion.wsMenuDia.IWcfMenuDia, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcfMenuDiaClient : System.ServiceModel.ClientBase<Presentacion.wsMenuDia.IWcfMenuDia>, Presentacion.wsMenuDia.IWcfMenuDia {
        
        public WcfMenuDiaClient() {
        }
        
        public WcfMenuDiaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WcfMenuDiaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfMenuDiaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfMenuDiaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Entidades.MenuDiaEntidad GuardarMenuDia(Entidades.MenuDiaEntidad menuDia) {
            return base.Channel.GuardarMenuDia(menuDia);
        }
        
        public System.Threading.Tasks.Task<Entidades.MenuDiaEntidad> GuardarMenuDiaAsync(Entidades.MenuDiaEntidad menuDia) {
            return base.Channel.GuardarMenuDiaAsync(menuDia);
        }
        
        public Entidades.MenuDiaEntidad[] DevolverListaMenuDia() {
            return base.Channel.DevolverListaMenuDia();
        }
        
        public System.Threading.Tasks.Task<Entidades.MenuDiaEntidad[]> DevolverListaMenuDiaAsync() {
            return base.Channel.DevolverListaMenuDiaAsync();
        }
        
        public Entidades.MenuDiaJoin[] DevolverListaMenuDiaJoin() {
            return base.Channel.DevolverListaMenuDiaJoin();
        }
        
        public System.Threading.Tasks.Task<Entidades.MenuDiaJoin[]> DevolverListaMenuDiaJoinAsync() {
            return base.Channel.DevolverListaMenuDiaJoinAsync();
        }
        
        public Entidades.MenuDiaEntidad DevolverMenuDiaPorId(int id) {
            return base.Channel.DevolverMenuDiaPorId(id);
        }
        
        public System.Threading.Tasks.Task<Entidades.MenuDiaEntidad> DevolverMenuDiaPorIdAsync(int id) {
            return base.Channel.DevolverMenuDiaPorIdAsync(id);
        }
        
        public bool EliminarMenuDia(int id) {
            return base.Channel.EliminarMenuDia(id);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarMenuDiaAsync(int id) {
            return base.Channel.EliminarMenuDiaAsync(id);
        }
        
        public Entidades.MenuDiaEntidad[] DevolverMenuDiaPorFecha(System.DateTime date) {
            return base.Channel.DevolverMenuDiaPorFecha(date);
        }
        
        public System.Threading.Tasks.Task<Entidades.MenuDiaEntidad[]> DevolverMenuDiaPorFechaAsync(System.DateTime date) {
            return base.Channel.DevolverMenuDiaPorFechaAsync(date);
        }
        
        public Entidades.SopasEntidad GuardarSopa(Entidades.SopasEntidad sopaDia) {
            return base.Channel.GuardarSopa(sopaDia);
        }
        
        public System.Threading.Tasks.Task<Entidades.SopasEntidad> GuardarSopaAsync(Entidades.SopasEntidad sopaDia) {
            return base.Channel.GuardarSopaAsync(sopaDia);
        }
        
        public Entidades.SopasEntidad[] DevolverListaSopas() {
            return base.Channel.DevolverListaSopas();
        }
        
        public System.Threading.Tasks.Task<Entidades.SopasEntidad[]> DevolverListaSopasAsync() {
            return base.Channel.DevolverListaSopasAsync();
        }
        
        public Entidades.SopasEntidad DevolverSopasPorId(int id) {
            return base.Channel.DevolverSopasPorId(id);
        }
        
        public System.Threading.Tasks.Task<Entidades.SopasEntidad> DevolverSopasPorIdAsync(int id) {
            return base.Channel.DevolverSopasPorIdAsync(id);
        }
        
        public bool EliminarSopa(int id) {
            return base.Channel.EliminarSopa(id);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarSopaAsync(int id) {
            return base.Channel.EliminarSopaAsync(id);
        }
        
        public Entidades.SopasEntidad DevolverIngredientesSopasPorId(int id) {
            return base.Channel.DevolverIngredientesSopasPorId(id);
        }
        
        public System.Threading.Tasks.Task<Entidades.SopasEntidad> DevolverIngredientesSopasPorIdAsync(int id) {
            return base.Channel.DevolverIngredientesSopasPorIdAsync(id);
        }
        
        public Entidades.SegundosEntidad GuardarSegundo(Entidades.SegundosEntidad segundo) {
            return base.Channel.GuardarSegundo(segundo);
        }
        
        public System.Threading.Tasks.Task<Entidades.SegundosEntidad> GuardarSegundoAsync(Entidades.SegundosEntidad segundo) {
            return base.Channel.GuardarSegundoAsync(segundo);
        }
        
        public Entidades.SegundosEntidad[] DevolverListaSegundos() {
            return base.Channel.DevolverListaSegundos();
        }
        
        public System.Threading.Tasks.Task<Entidades.SegundosEntidad[]> DevolverListaSegundosAsync() {
            return base.Channel.DevolverListaSegundosAsync();
        }
        
        public Entidades.SegundosEntidad DevolverSegundosPorId(int id) {
            return base.Channel.DevolverSegundosPorId(id);
        }
        
        public System.Threading.Tasks.Task<Entidades.SegundosEntidad> DevolverSegundosPorIdAsync(int id) {
            return base.Channel.DevolverSegundosPorIdAsync(id);
        }
        
        public bool EliminarSegundo(int id) {
            return base.Channel.EliminarSegundo(id);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarSegundoAsync(int id) {
            return base.Channel.EliminarSegundoAsync(id);
        }
        
        public Entidades.SegundosEntidad DevolverIngredientesSegundoPorId(int id) {
            return base.Channel.DevolverIngredientesSegundoPorId(id);
        }
        
        public System.Threading.Tasks.Task<Entidades.SegundosEntidad> DevolverIngredientesSegundoPorIdAsync(int id) {
            return base.Channel.DevolverIngredientesSegundoPorIdAsync(id);
        }
        
        public Entidades.BebidasEntidad GuardarBebida(Entidades.BebidasEntidad bebidas) {
            return base.Channel.GuardarBebida(bebidas);
        }
        
        public System.Threading.Tasks.Task<Entidades.BebidasEntidad> GuardarBebidaAsync(Entidades.BebidasEntidad bebidas) {
            return base.Channel.GuardarBebidaAsync(bebidas);
        }
        
        public Entidades.BebidasEntidad[] DevolverListaBebidas() {
            return base.Channel.DevolverListaBebidas();
        }
        
        public System.Threading.Tasks.Task<Entidades.BebidasEntidad[]> DevolverListaBebidasAsync() {
            return base.Channel.DevolverListaBebidasAsync();
        }
        
        public Entidades.BebidasEntidad DevolverBebidasPorId(int id) {
            return base.Channel.DevolverBebidasPorId(id);
        }
        
        public System.Threading.Tasks.Task<Entidades.BebidasEntidad> DevolverBebidasPorIdAsync(int id) {
            return base.Channel.DevolverBebidasPorIdAsync(id);
        }
        
        public bool EliminarBebida(int id) {
            return base.Channel.EliminarBebida(id);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarBebidaAsync(int id) {
            return base.Channel.EliminarBebidaAsync(id);
        }
        
        public Entidades.BebidasEntidad DevolverIngredientesBebidaPorId(int id) {
            return base.Channel.DevolverIngredientesBebidaPorId(id);
        }
        
        public System.Threading.Tasks.Task<Entidades.BebidasEntidad> DevolverIngredientesBebidaPorIdAsync(int id) {
            return base.Channel.DevolverIngredientesBebidaPorIdAsync(id);
        }
        
        public Entidades.EntradasEntidad GuardarEntrada(Entidades.EntradasEntidad entrada) {
            return base.Channel.GuardarEntrada(entrada);
        }
        
        public System.Threading.Tasks.Task<Entidades.EntradasEntidad> GuardarEntradaAsync(Entidades.EntradasEntidad entrada) {
            return base.Channel.GuardarEntradaAsync(entrada);
        }
        
        public Entidades.EntradasEntidad[] DevolverListaEntrada() {
            return base.Channel.DevolverListaEntrada();
        }
        
        public System.Threading.Tasks.Task<Entidades.EntradasEntidad[]> DevolverListaEntradaAsync() {
            return base.Channel.DevolverListaEntradaAsync();
        }
        
        public Entidades.EntradasEntidad DevolverEntradasPorId(int id) {
            return base.Channel.DevolverEntradasPorId(id);
        }
        
        public System.Threading.Tasks.Task<Entidades.EntradasEntidad> DevolverEntradasPorIdAsync(int id) {
            return base.Channel.DevolverEntradasPorIdAsync(id);
        }
        
        public bool EliminarEntrada(int id) {
            return base.Channel.EliminarEntrada(id);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarEntradaAsync(int id) {
            return base.Channel.EliminarEntradaAsync(id);
        }
        
        public Entidades.EntradasEntidad DevolverIngredientesEntradaPorId(int id) {
            return base.Channel.DevolverIngredientesEntradaPorId(id);
        }
        
        public System.Threading.Tasks.Task<Entidades.EntradasEntidad> DevolverIngredientesEntradaPorIdAsync(int id) {
            return base.Channel.DevolverIngredientesEntradaPorIdAsync(id);
        }
        
        public Entidades.PedidosEntidad GuardarPedido(Entidades.PedidosEntidad pedido) {
            return base.Channel.GuardarPedido(pedido);
        }
        
        public System.Threading.Tasks.Task<Entidades.PedidosEntidad> GuardarPedidoAsync(Entidades.PedidosEntidad pedido) {
            return base.Channel.GuardarPedidoAsync(pedido);
        }
    }
}
